dist: trusty
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: google-trash.deb
  skip_cleanup: true
  on:
    tags: true

script:
  - |
    sudo apt-get update
    sudo apt -get install cmake curl
    git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc /home/travis/grpc
    pushd /home/travis/grpc
    git submodule update --init
    popd
    mkdir -p /home/travis/build/
    mkdir -p /home/travis/google-trash/DEBIAN
    pushd /home/travis/build/
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/travis/google-trash /home/travis/grpc
    make
    make install
    popd
    cp ./control /home/travis/google-trash/DEBIAN/
    dpkg-deb --build /home/travis/google-trash
    mv /home/travis/google-trash.deb .
    sudo dpkg -i google-trash.deb
